version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - replyme_network
    env_file: .env
    depends_on:
      - db

  php_api:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - replyme_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: replayme_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - replyme_network

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - replyme_network

  helpdesk_mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - helpdesk_mariadb_data:/var/lib/mysql
    networks:
      - replyme_network

  helpdesk_redis:
    image: redis:alpine
    networks:
      - replyme_network

  helpdesk_app:
    image: frappe/bench:latest
    command: bash /workspace/frappe_init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - "8001:8000"
      - "9000:9000"
    networks:
      - replyme_network
    depends_on:
      - helpdesk_mariadb
      - helpdesk_redis

volumes:
  db_data:
  helpdesk_mariadb_data:

networks:
  replyme_network:
    driver: bridge
