version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - replyme_network
    env_file: .env
    depends_on:
      - db

  php_api:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - replyme_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: replayme_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - replyme_network

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - replyme_network

volumes:
  db_data:

networks:
  replyme_network:
    driver: bridge
